version: '3'
services:
  trivia_dbms:
    image: postgres:10.10-alpine
    container_name: trivia_dbms
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
